abstract class TotalIncomeExpenseState {}

class TotalIncomeExpenseInitialState extends TotalIncomeExpenseState {}
class TotalIncomeExpenseDoneState extends TotalIncomeExpenseState{}
class TotalIncomeExpenseEmptyState extends TotalIncomeExpenseState{}
class TotalIncomeExpenseDataLoading extends TotalIncomeExpenseState{}
class TotalIncomeExpenseDataLoaded extends TotalIncomeExpenseState{}